### PR TITLE
Update the Email address under issue#27

### PR DESCRIPTION
**Pull request by CharryDinz**

### CODE REVIEW

**Review by misterhackney — CHANGES_REQUESTED** [review]
Change this to an official corporate email address.

**Comment by CharryDinz** [comment]
Can I ask for the official corporate email address, please? Because, it's not available on the silkcorp.org website. Thanks

**Comment by misterhackney** [comment]
always use info@
So, here will be info@silkcorp.org

**Comment by CharryDinz** [comment]
The email address has been updated.

**Pull request merged**
